using Microsoft.EntityFrameworkCore.Migrations;

namespace BlogMind.Migrations
{
    public partial class SeedCommentsTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium', (SELECT ID FROM Posts WHERE Title = 'Protesters set Minneapolis police station ablaze'), '4f841339-9e98-4a63-9729-99d8f8eue202')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et', (SELECT ID FROM Posts WHERE Title = 'Moscow more than doubles city''s Covid-19 death toll'), '4f841339-9e98-4a63-9729-99d8f8eue202')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione', (SELECT ID FROM Posts WHERE Title = 'Twitter hides Trump tweet for ''glorifying violence'''), '4f841339-9e98-4a63-9729-99d8f8eue202')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('doloribus at sed quis culpa deserunt consectetur qui praesentium\naccusamus fugiat dicta\nvoluptatem rerum ut voluptate autem\nvoluptatem repellendus aspernatur dolorem in', (SELECT ID FROM Posts WHERE Title = 'Facebook dominates cases of recorded social media grooming'), 'df037be1-bf79-4cd2-bi6e-677ea7f9r0e4')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('ut dolorum nostrum id quia aut est\nfuga est inventore vel eligendi explicabo quis consectetur\naut occaecati repellat id natus quo est\nut blanditiis quia ut vel ut maiores ea', (SELECT ID FROM Posts WHERE Title = 'Trading Standards squad targets anti-5G USB stick'), 'df037be1-bf79-4cd2-bi6e-677ea7f9r0e4')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('expedita maiores dignissimos facilis\nipsum est rem est fugit velit sequi\neum odio dolores dolor totam\noccaecati ratione eius rem velit', (SELECT ID FROM Posts WHERE Title = 'Trump signs executive order targeting Twitter after fact-checking row'), 'df037be1-bf79-4cd2-bi6e-677ea7f9r0e4')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('iste ut laborum aliquid velit facere itaque\nquo ut soluta dicta voluptate\nerror tempore aut et\nsequi reiciendis dignissimos expedita consequuntur libero sed fugiat facilis', (SELECT ID FROM Posts WHERE Title = 'Thousands of TalkTalk users hit by internet problems'), '4u871339-0e98-4k63-9929-99d8f0eue202')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('deleniti aut sed molestias explicabo\ncommodi odio ratione nesciunt\nvoluptate doloremque est\nnam autem error delectus', (SELECT ID FROM Posts WHERE Title = 'Huawei executive suffers US extradition blow'), '4u871339-0e98-4k63-9929-99d8f0eue202')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('qui ipsa animi nostrum praesentium voluptatibus odit\nqui non impedit cum qui nostrum aliquid fuga explicabo\nvoluptatem fugit earum voluptas exercitationem temporibus dignissimos distinctio\nesse inventore reprehenderit quidem ut incidunt nihil necessitatibus rerum', (SELECT ID FROM Posts WHERE Title = 'Zipline drones deliver supplies and PPE to US hospitals'), '4u871339-0e98-4k63-9929-99d8f0eue202')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('voluptates provident repellendus iusto perspiciatis ex fugiat ut\nut dolor nam aliquid et expedita voluptate\nsunt vitae illo rerum in quos\nvel eligendi enim quae fugiat est', (SELECT ID FROM Posts WHERE Title = 'Rainfall shutdown during lockdown'), 'ef047be3-bd75-4cw2-bt6e-677er7f9r7e4')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('repudiandae repellat quia\nsequi est dolore explicabo nihil et\net sit et\net praesentium iste atque asperiores tenetur', (SELECT ID FROM Posts WHERE Title = 'Biggest UK solar plant approved'), 'ef047be3-bd75-4cw2-bt6e-677er7f9r7e4')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('incidunt sapiente eaque dolor eos\nad est molestias\nquas sit et nihil exercitationem at cumque ullam\nnihil magnam et', (SELECT ID FROM Posts WHERE Title = 'Coronavirus: Rishi Sunak urged by MPs to extend self-employed help'), 'ef047be3-bd75-4cw2-bt6e-677er7f9r7e4')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('quia incidunt ut\naliquid est ut rerum deleniti iure est\nipsum quia ea sint et\nvoluptatem quaerat eaque repudiandae eveniet aut', (SELECT ID FROM Posts WHERE Title = 'Nasa SpaceX launch: Big day called off because of weather'), '4f847339-9e68-4o73-9429-97d8f1eue707')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('aut vero est\ndolor non aut excepturi dignissimos illo nisi aut quas\naut magni quia nostrum provident magnam quas modi maxime\nvoluptatem et molestiae', (SELECT ID FROM Posts WHERE Title = 'Coronavirus: Rishi Sunak urged by MPs to extend self-employed help'), '4f847339-9e68-4o73-9429-97d8f1eue707')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('facere repudiandae vitae ea aut sed quo ut et\nfacere nihil ut voluptates in\nsaepe cupiditate accusantium numquam dolores\ninventore sint mollitia provident', (SELECT ID FROM Posts WHERE Title = 'Trump signs executive order targeting Twitter after fact-checking row'), 'rf547ge3-wt75-4sw5-bv6r-647er7f9d7e5')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('aut culpa quaerat veritatis eos debitis\naut repellat eius explicabo et\nofficiis quo sint at magni ratione et iure\nincidunt quo sequi quia dolorum beatae qui', (SELECT ID FROM Posts WHERE Title = 'New date agreed for UN climate summit in Glasgow'), 'rf547ge3-wt75-4sw5-bv6r-647er7f9d7e5')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('exercitationem et id quae cum omnis\nvoluptatibus accusantium et quidem\nut ipsam sint\ndoloremque illo ex atque necessitatibus sed', (SELECT ID FROM Posts WHERE Title = 'Isle of Wight pterosaur species fossil hailed as UK first'), '2f347539-6e63-4o53-4469-57d8g1eue608')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('occaecati laudantium ratione non cumque\nearum quod non enim soluta nisi velit similique voluptatibus\nesse laudantium consequatur voluptatem rem eaque voluptatem aut ut\net sit quam', (SELECT ID FROM Posts WHERE Title = 'World''s deepest octopus captured on camera'), '2f347539-6e63-4o53-4469-57d8g1eue608')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('illum et alias quidem magni voluptatum\nab soluta ea qui saepe corrupti hic et\ncum repellat esse\nest sint vel veritatis officia consequuntur cum', (SELECT ID FROM Posts WHERE Title = 'Coronavirus: France set to roll out contact-tracing app before UK'), 'xs545ge2-et79-3st5-yv6t-247er7g9d6e9')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('perferendis omnis esse\nvoluptate sit mollitia sed perferendis\nnemo nostrum qui\nvel quis nisi doloribus animi odio id quas', (SELECT ID FROM Posts WHERE Title = 'Uber destroys thousands of bikes and scooters'), 'xs545ge2-et79-3st5-yv6t-247er7g9d6e9')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('cum esse odio nihil reiciendis illum quaerat\nest facere quia\noccaecati sit totam fugiat in beatae\nut occaecati unde vitae nihil quidem consequatur', (SELECT ID FROM Posts WHERE Title = 'Moscow more than doubles city''s Covid-19 death toll'), '4i387037-5e90-6o03-0468-95d8g1eue860')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('deserunt cumque laudantium\net et odit quia sint quia quidem\nquibusdam debitis fuga in tempora deleniti\nimpedit consequatur veniam reiciendis autem porro minima', (SELECT ID FROM Posts WHERE Title = 'Facebook dominates cases of recorded social media grooming'), '4i387037-5e90-6o03-0468-95d8g1eue860')");

            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('necessitatibus libero occaecati\nvero inventore iste assumenda veritatis\nasperiores non sit et quia omnis facere nemo explicabo\nodit quo nobis porro', (SELECT ID FROM Posts WHERE Title = 'Trump signs executive order targeting Twitter after fact-checking row'), 'qd525gr2-gt26-1gt8-hm6t-737er7g6o8j6')");
            migrationBuilder.Sql("INSERT INTO Comments (Body, PostId, AppUserId) VALUES ('nulla quo itaque beatae ad\nofficiis animi aut exercitationem voluptatum dolorem doloremque ducimus in\nrecusandae officia consequuntur quas\naspernatur dolores est esse dolores sit illo laboriosam quaerat', (SELECT ID FROM Posts WHERE Title = 'Protesters set Minneapolis police station ablaze'), 'qd525gr2-gt26-1gt8-hm6t-737er7g6o8j6')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Comments WHERE AppUserId IN ('4f841339-9e98-4a63-9729-99d8f8eue202' ,'df037be1-bf79-4cd2-bi6e-677ea7f9r0e4' ,'4u871339-0e98-4k63-9929-99d8f0eue202' ,'ef047be3-bd75-4cw2-bt6e-677er7f9r7e4' ,'4f847339-9e68-4o73-9429-97d8f1eue707','rf547ge3-wt75-4sw5-bv6r-647er7f9d7e5', '2f347539-6e63-4o53-4469-57d8g1eue608', 'xs545ge2-et79-3st5-yv6t-247er7g9d6e9', '4i387037-5e90-6o03-0468-95d8g1eue860', 'qd525gr2-gt26-1gt8-hm6t-737er7g6o8j6')");
        }
    }
}
